import React from "react";
import Head from "next/head";

export default function Layout({ children, title }) {
  return (
    <>
      <Head>
        <title>{title ? title + "- ANT-Ecommerce" : "ANT Ecommerce"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex min-h-screen flex-col justify-between">
        <header>Header</header>

        <main>{children}</main>

        <footer>footer</footer>
      </div>
    </>
  );
}
