import  { useState, useEffect, useContext} from "react";
import Head from "next/head";
import Link from "next/link";
import  { Store }  from "@/utils/Store";

export default function Layout({ children, title }) {
    const { state } = useContext(Store);
    const { cart } = state;
    const [year, setYear] = useState();
    const [cartItemsCount, setCartItemsCount] = useState(0);

    useEffect(() => {
       setCartItemsCount(cart.cartItems.reduce((a, c) => a + c.quantity, 0))
       
        const interval = setInterval(() => {
            setYear(new Date().getFullYear())
        }, 1000)
        return () => clearInterval(interval)
        
    }, [cart.cartItems])

  return (
    <>
      <Head>
        <title>{title ? title + "- ANT-Ecommerce" : "ANT Ecommerce"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex min-h-screen flex-col justify-between">
        <header>
          <nav className="flex h-12 items-center px-4 justify-between shadow-md">
            <Link href="/">
              <p className="text-lg font-bold text-black">ANT Ecommerce</p>
            </Link>
            <div className="flex">
              <Link href="/cart">
                <p className="p-2">
                    Cart
                    {cartItemsCount > 0 && (
                        <span className="ml-1 rounded-full bg-red-600 px-2 py-1 text-xs font-bold text-white">
                            {cartItemsCount}
                        </span>
                  )}
                </p>
              </Link>
              <Link href="/login">
                <p className="p-2">Login</p>
              </Link>
            </div>
          </nav>
        </header>

        <main className="container m-auto mt-4 px-4">{children}</main>

        <footer className="flex h-10 justify-center items-center shadow-inner">
          <p>Copyright © {year}  ANT Ecommerce</p>
          </footer>
      </div>
    </>
  );
}
